//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 11:42:10 PM MSK 
//


package ru.medvedev.labxml.pojo;

import java.util.List;

public class ContinentType {

    private String name;
    private Float area;
    private List<CountryType> countries;

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }


    public Float getArea() {
        return area;
    }

    public void setArea(Float value) {
        this.area = value;
    }

    public List<CountryType> getCountries() {
        return this.countries;
    }

    public void setCountries(List<CountryType> countries) {
        this.countries = countries;
    }
}
